### ISSUE TITLE
Agile Tracking - sprint end

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Spartanizer#1086]
The current sprint ends on next week, so we have to close all the open issues for milestone 2.8. Please close the issues as soon as you can, preferably until 22/1. If new bugs appear and they are not yours, put them on me and I will assign them.

**Comment by yossigil** [comment]
💯

**Comment by ravivos** [comment]
referencing #1084

**Comment by yuvalsimon** [comment]
I ignored all the expanders that use namespace because it made lots of errors. Not sure if it is problem in the expanders or in the name generator. 
Please from now until end of the sprint, before you commit expander into the inflater firstly run the athenizer on the project (not only the tests, but also them), and there should not be any errors on this. (if there is then don't commit the expander to inflater). 
Also need to disable LongIfExpander and enable TernaryPushup, I had problems with git so couldn't commit. 
Check https://github.com/SpartanRefactoring/Spartanizer/commit/efde6d6e7a41f852a1a4c9f4f9c8433c07721357 to see the expanders I disabled.

**Comment by yossigil** [comment]
@mdoron : take note that you are blocking the entire team. @orimarco @yh-github @idabran @AdiOmari  
👎

**Comment by mdoron** [comment]
@yossigil. Yuval rechecked it and it wasn't with the name generation... 
![image](https://cloud.githubusercontent.com/assets/12110390/22184301/a964e304-e0d7-11e6-80ed-b45dc5ca4cc9.png)

@orimarco @yh-github @idabran @AdiOmari

**Comment by yossigil** [comment]
Doron: this is our life. Sometimes tests we wrote suddenly fail. 

In a cooperative team work, it is better to either  

- Name the guy who broke the test convention and ask him to fix or take note, etc.
- Post  a warning to all, saying that this refactoring is breaking tests.
- Take charge of  your own code and tests, even if they were change by others.

It is not acceptable to say: "Some changed the tests", which can mean to many: **it is someone's else's fault! I did not do it! Even my friends say that I am a good guy!  I do not care who this person is, since I am a good guy.  I did not want to do this, since I thought this other person did something of purpose** 

Your response can be easily mistaken to abandoing personal responsiblity, trying to delegate it to unfair circumstances.
