### ISSUE TITLE
Rename short/currency variable names - Decleration

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1107]
```Java
int f() {
  int $ = 5;
  x($);
  return $;
}
```
==>
```Java
int f() {
  int res = 5;
  x(res);
  return res;
}

**Comment by yuvalsimon** [comment]
Probably closed but need #1241 to work properly when athenizing whole project.

**Comment by yuvalsimon** [comment]
All tests fail when adding this to toolbox since it changes the names of most variables to the conventions. I think of disabling it in all tests except the test case of this bloater. What do you think @OriRoth ? I think to add it to Bloater.Renaming category and disabling this category in tests by default.

**Comment by OriRoth** [comment]
We don't have that much bloating tests. We can add `using(...)` to all of them.

**Comment by yuvalsimon** [comment]
I think it's better to disable it in test by default, we also might change the renaming conventions so we don't want all tests to be affected by that. I have to commit some new code for this when my Eclipse is fixed, but we will disable this bloater temporarily.
