### ISSUE TITLE
Mnemonics for cent ¢ and  lambda λ

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1128]
We need short cuts for these, and main menu items:

- Insert cent ¢ XXXX 
- Insert lambda λ YYYY

Where XXXX are good menemonics, ideally Ctrl-C and and Ctrl-L, but I presume these are taken

**Comment by OriRoth** [comment]
What exactly is the operation you want? Textually adding those characters?

**Comment by yossigil** [comment]
Yes. (is there something I miss?)

**Comment by OriRoth** [comment]
Done, see `CharacterShortcut`. Note that in order to make changes to the current scheme, one should change `plugin.xml` as well, not this file solely.
At the moment you can insert a single `¢` to your code by typing `ctrl+alt+c` and `λ` by `ctrl+alt+l`. `ctrl+c/l` are already taken... there might be more *comfortable* shortcuts, such as `ctrl+alt+q/w/e`.
Another option I though of is a single shortcut that would open a small menu, from which the user would be able to select a special character. One can get used to it, and I think it is a "cleaner" implementation.
If you want to make changes to the shortcuts, tell me and I'll make them in `plugin.xml`.

**Comment by OriRoth** [comment]
Also notice parallel shortcuts are provided by some operating systems- for example, there is a simple shortcut (`ctrl+something`) to ¢ in MAC. In Windows it is `alt+0+1+6+2`... is it configurable? Probably in some OS...

**Comment by yossigil** [comment]
Can  you please add this to the menu, no chance for me to remember this?

**Comment by OriRoth** [comment]
Spartanize -> ¢
#got_hacked

**Comment by OriRoth** [comment]
@dormaayan http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fworkbench_advext_contexts.htm
