### ISSUE TITLE
Yet another if tipper

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1129]
```Java
if (a) {
  <block 1>
} else if (b) {
  <block 2>
} else {
  <block 1>
}
```
==>
```Java
if (a || !b) {
  <block 1>
} else if (b) {
  <block 2>
}
```

**Comment by OriRoth** [comment]
@NivShalmon BEWARE!
```Java
if (b1)
  if (b2)
    f1();
  else if (b3)
    f2();
  else
    f1();
else
  g();
```
!=
```Java
if (b1)
  if (b2 || !b3)
    f1();
  else if (b3)
    f2();
else
  g();
```

Also `b3` in this case should have no side effects.

See `sideEffects#free` and `iz#blockEssential`

**Comment by yossigil** [comment]
I am here

**Comment by NivShalmon** [comment]
This tipper got a bit weird since I needed to run `iz#blockEssential` on an IfStatement that isn't part of an ast yet, I solved this by putting it in the original ast momenterally, but I'm not sure this is safe, so I added a try finally block in this second commit just to be safe and make sure the ast is returned to it's original form.

**Comment by OriRoth** [comment]
This is generally not recommended (we don't really know the implications). I'll deal with it.

**Comment by NivShalmon** [comment]
figured as much, I think this can be solved by going up the tree as far as `iz#blockEssential` needs and copying it from there down. I belive thats as long as the parents are still if statements? I'll try this tommorow and see if I can make this work.

**Comment by yossigil** [comment]
I think @NivShalmon  pretty much finished this

**Comment by NivShalmon** [comment]
The tipper no longer changes the original ast, so it's done
