### ISSUE TITLE
Specific tipper test - parent class

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#1172]

**Comment by yossigil** [comment]
Huh? What does this mean?

**Comment by NivShalmon** [comment]
This relates to the robust testing we talked about yesterday.
Usually, when writing unit tests, a test class will have tests for one tipper. Right now, in order to test only that tipper (and not the entire Toolbox), we need to write .using() before any .gives() or .stays() call. This is both tedious and enlarges the code for no real reason.
So, we thought to add a parent class to the test that gives us a trimmingOf().using() in one method, in order to keep tests shorter.
The goal of this is to still write tests the same way (using trimmingOf().gives()) but get tests only fot a singel tipper when needed, to make writing robust tests easier.

**Comment by yossigil** [comment]
Great Idea! We should somehow defunct trimmingOf and move to trimmingWith

**Comment by yossigil** [comment]
I think I once started working on this. Look for class 'trim'

**Comment by OriRoth** [comment]
We observed test classes usually test one tipper, so we intend to create test classes that use a specific tipper so the tests may be written fluently. Something like this:
```Java
Class MyTipperTest extends TipperTest {
  @Override public Tipper<?> tipper() {
    return new MyTipper();
  }

  @Test public void test1() {
    trimmingOf(...).gives(...);
    // NOT the regular trimmingOf, but a method of TipperTest that uses declared tipper
  }
}
```

**Comment by yossigil** [comment]
great idea

**Comment by NivShalmon** [comment]
First version for tippers is up along with a usage example in the tests of #1146. That example also demonstrates how, when trimming the same input, TrimmerTestUtils's trimmingOf gives a different result than TipperTests's trimmingOf.
Right now this works for tippers. I see four ways of extending this to bloaters, using the current methods TrimmingOperand gives:

1. make a different class for bloters, that's mostly the same, using `usingBloater` instead of `usingTipper`
2. have the user tell us whether he tests a bloater/tipper (for example overriding another method)
3. have the user tell us the class the tipper/bloater works on (then the general `using` can be used instead of the specific `usingtipper/bloater`)
4. understand the class the tipper/bloater works on using reflection (I'm not sure how to do this)

Options 2,3 make the user write more code while option 1 cuases code duplication. Option 4 seems optimal, but is also harder to implement and may slow down the tests slightly, which is why we didn't use generics and reflection to get the Tipper in the first place.

Also, TipperTest currently depends on `TrimmingOperads#usingTipper` returning the object it works on. This is currect in the current implementation but may change. The other option I found is to duplicate it's implementation in my code, which seemed even worse to me.

**Comment by NivShalmon** [comment]
I went with option 3 despite that adding a lot of code for the user to write since it adds a very important utility (in my opinion)- a tipper can be tested before it is added to the toolbox. This should allow us to effectivly seperate integration tests from unit tests, and only start the integration of a tipper/bloater into the toolbox after it passes unit tests.
This also allows the same class to be used for tippers and bloates since it now uses the universal `TrimmerOperand#using` method rather than the specific `TrimmerOperand#usingTipper/Bloater` methods.

@yossigil I can change this to options 1,2 relatively quickly. I'll bring this up during the team's meeting tommorow to ask everyone what they think about it and decide which version we prefer. Option 4 is strictly better than this (one less function the user has to implement), but I'm still not sure how to do it or if it is even possible, so if we choose that one it probably won't be done by monday.

**Comment by yossigil** [comment]
Superb job. I fully agree

**Comment by OriRoth** [comment]
@NivShalmon you may post an announcement in the Telegram group with a simple example so people will start to use it.
