### ISSUE TITLE
Spartanizer preferences GUI bug

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Spartanizer#1219]
While working on the project's wiki I noticed that on 'Refactor->Spartanizer->Preferences' the description shown for a tipper is it's name even though it has a 'description()' method. And no example is shown even that there's 'examples()' method.
For example: for ArrayAccessAndIncrement tipper

![screen shot 2017-04-04 at 12 19 32](https://cloud.githubusercontent.com/assets/23155308/24649985/79cc95aa-1931-11e7-81e1-85611146b725.png)

![screen shot 2017-04-04 at 12 19 40](https://cloud.githubusercontent.com/assets/23155308/24649986/7b103598-1931-11e7-82e5-25ea7f0b8f2b.png)

**Comment by OriRoth** [comment]
The description is bad because `description()` is not overrided for `ArrayAccessAndIncrement`, see #1130.
I get the examples fine... do you run the Spartanizer as plugin debug? The last release may not contain examples for this tipper.
![examples](https://cloud.githubusercontent.com/assets/15183108/24650536/2a960f0a-1933-11e7-8d81-8d03c3d35898.jpg)

**Comment by tomerdragucki** [comment]
Yeah I checked it on the last release my bad. close? @OriRoth
