### ISSUE TITLE
Choosing a name - Athenizer/Zoomer

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Spartanizer#1239]
Hey Guys.
We are in a dilemma about the name choosing of our project.
I assume you are all familiar with our project of course, because you have all taken part in it or have used it, so please vote as an emoji on this comment for the name you prefer:
👍  - "Athenizer"
🎉  - "The Zoomer"

**Comment by ravivos** [comment]
First three votes will decide

**Comment by tomnof** [comment]
👍

**Comment by ortroyaner** [comment]
Since I've been assigned I'll post about my opinion:
TL;DR - Athenizer. 👍 

I think that this name's connection to the Spartanizer project is very intuitive, and it's easier to understand the project's goals with this name.
About "The Zoomer", the "The" prefix seems a little bit unprofessional for me (usually, if "The" prefix comes before a term which is not a consensus (e.g. "The Amazing Spider-Man"), it smells fishy). Furthermore, I think it relate more to the camera and filming world and less to coding.
Thats why I prefer sticking with Athenizer.

**Comment by ravivos** [comment]
So "Athenizer" it is
