### ISSUE TITLE
Make SingleFlater use monitor

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#1249]
Defunct the exception listener. Use java logging instead

**Comment by yossigil** [comment]
start here
![image](https://cloud.githubusercontent.com/assets/12775400/24959955/f119ebfa-1f9c-11e7-9234-6212df28da2a.png)

**Comment by oran1248** [comment]
I don't know if i do it right. @yossigil @OriRoth - please approve.
All the tests pass. 
Should I refactor out Tap and Taps? as it the same in TrimmerMonitor and SingleFlaterMonitor.

**Comment by OriRoth** [comment]
I've created a test for a testing mechanism that used the exception listener: `doesNotCrash`. It was very problematic to begin with, because a bug in the testing mechanism causes the test to *pass* rather than fail. See #950 

@yossigil we should decide whether to register an exception listener to `stays` and `gives` as well (we probably do), in that case we should test this too... but that is another issue I guess.

One more thing: I think I wrote the test class properly (using designated `FailingTipper`)... Note me if there is some bug.

**Comment by OriRoth** [comment]
Second thought: #950 is not closed, so it might be @yuvalsimon 's TODO....

**Comment by yossigil** [comment]
@oran1248 ?

**Comment by oran1248** [comment]
I don't understand, what is the problem?
There is a problem with what I have done in SingleFlater?

**Comment by OriRoth** [comment]
You removed some code of Yuval I think... he will probably would need to
use your listener instead

On Apr 13, 2017 17:48, "oran1248" <notifications@github.com> wrote:

I don't understand, what is the problem?
There is a problem with what I have done in SingleFlater?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SpartanRefactoring/Spartanizer/issues/1249#issuecomment-293917456>,
or mute the thread

**Comment by oran1248** [comment]
@OriRoth , can you please put your finger on such code?
In the first commit I replaced try...catch with robust.ly
In the second commit I have integrated monitor into SingleFlater

**Comment by OriRoth** [comment]
I have commented in the relevant commit.
@oran1248 it is a work for #950. If you want you can help Yuval use your code by self-assigning to the issue. Anyway, you may leave a comment on #950 describing how to use your listener.
