### ISSUE TITLE
Bug in inlining?

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#155]
Why no inlining here?
```
		for (int i = 0; i < versionNumbers.length; ++i) {
			final String nb = versionNumbers[i];
			$[i] = Integer.parseInt(nb);
		}

````

**Comment by OriRoth** [comment]
OK I think it is something I did (in DeclarationInitializerStatementTerminatingScope). If you'll remove the "final" it would work just fine.

The original problem was inlining final variables into methods' scopes. Complicating things is Java 8's *effectively final* (http://codeinventions.blogspot.co.il/2014/07/difference-between-final-and.html). Consider the following cases:
```
void h(int x) {
  new Object() {
    @Override
    public int hashCode() {
      return x;
    }
  };
}
```
Will compile (effectively final).
```
void h(int x) {
  ++x;
  final int y = x;
  new Object() {
    @Override
    public int hashCode() {
      return y;
    }
  };
}
```
Will compile (final).
```
void h(int x) {
  ++x;
  new Object() {
    @Override
    public int hashCode() {
      return x;
    }
  };
}
```
Won't compile after inlining. My solution was to disallow finals inlining - the idea is not to discard the final attribute. Other solution may be implemented (disallowing inlining into class instance creation, for example).
The relevant code line:
```
for (final IExtendedModifier m : step.modifiers((VariableDeclarationStatement) f.getParent()))
  if (m.isModifier() && ((Modifier) m).isFinal())
    return null;
```

**Comment by yossigil** [comment]
Brilliant analysis.
Final variables are the easiest to inline. Just avoid anonymous classes

**Comment by yossigil** [comment]
Add tests, including all the above examples to  class
`Issue155Test`

**Comment by OriRoth** [comment]
OK but I need a clarification - do you want to create a new test class for each issue from now on? in a new file? (also for issue #142)

**Comment by yossigil** [comment]
Only from now on. I should add `trimming...to` to the template.

**Comment by OriRoth** [comment]
Added test class Issue155Test. Contains example from above + relevant test cases from TrimmerTest (all I could find)

**Comment by yossigil** [comment]
No, it is not mandatory to open test class for each issue, but it often helps. At your discretion

**Comment by yossigil** [comment]
@NivShalmon : how are we on this one?

**Comment by NivShalmon** [comment]
The test for the above case doesn't pass yet, but there is some inlining done now. The result of fully spartanizing the above code is:
'''JAVA
for (int i = 0; i < versionNumbers.length; ++i, $[i] = Integer.parseInt(nb)) {
	final String nb = versionNumbers[i];
}
'''
I'm not sure which tipper did this, but I think this is wrong since now i is increased before the assingment into $[i], which can cause an out of boundry access easily. Also, the block isn't removed for some reason.

**Comment by yossigil** [comment]
If you run the tipper test, you will get reports in the console, telling you which tipper was applied.

**Comment by NivShalmon** [comment]
The test fails because ConvertForWithLastStatementUpdateToFor tips before DeclarationInitializerStatementTerminatingScope does. When the former is disabled, the test passes, but I don't know how to change their order while executing. @yossigil any ideas?
@sakopzon the inlining ConvertForWithLastStatementUpdateToFor is wrong here. This seems related to #310

**Comment by OriRoth** [comment]
Check out the `ExcluderManager` feature. You can ask @sakopzon about it and about the order of spartanization execution, or talk to me.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
@sakopzon

**Comment by NivShalmon** [comment]
I tried using `ExclusionManager` in any way I could think of but it doesn't seem to work. I think the problem is that I'm trying to exclude a parent of the current node.
When running the test, this is the what trimmingOf prints:

VISIT: 'public final class C{public void m(){for(int i=0;i<versionNumbers.length;++i){final String nb=versionNumbers[i];$[i]=Integer.parseInt(nb);}}}' [174] (TypeDeclaration) parent = CompilationUnit
VISIT: 'public void m(){for(int i=0;i<versionNumbers.length;++i){final String nb=versionNumbers[i];$[i]=Integer.parseInt(nb);}}' [139] (MethodDeclaration) parent = TypeDeclaration
VISIT: '{for(int i=0;i<versionNumbers.length;++i){final String nb=versionNumbers[i];$[i]=Integer.parseInt(nb);}}' [124] (Block) parent = MethodDeclaration
VISIT: 'for(int i=0;i<versionNumbers.length;++i){final String nb=versionNumbers[i];$[i]=Integer.parseInt(nb);}' [121] (ForStatement) parent = Block
        File: null
       Tipper: ConvertForWithLastStatementUpdateToFor
       Named: ConvertForWithLastStatementUpdateToFor
        Kind: Canonicalization
   Described: Convert the while about '(i < versionNumbers.length)' to a traditional for(;;)
 Can tip: true
    Suggests: [51, 172]
      Before: Events:

       After: Events:
{
  for (int i=0; i < versionNumbers.length; ++i) {
    final String nb=versionNumbers[i];
    $[i]=Integer.parseInt(nb);
  }
}
 - statements:  [list change
	 [replaced: for (int i=0; i < versionNumbers.length; ++i) {
  final String nb=versionNumbers[i];
  $[i]=Integer.parseInt(nb);
}
 -> for (int i=0; i < versionNumbers.length; ++i, $[i]=Integer.parseInt(nb)) {
  final String nb=versionNumbers[i];
}
]
]


VISIT: 'int i=0' [9] (VariableDeclarationExpression) parent = ForStatement
VISIT: 'i=0' [5] (VariableDeclarationFragment) parent = VariableDeclarationExpression
VISIT: 'i<versionNumbers.length' [25] (InfixExpression) parent = ForStatement
VISIT: '++i' [3] (PrefixExpression) parent = ForStatement
VISIT: '{final String nb=versionNumbers[i];$[i]=Integer.parseInt(nb);}' [73] (Block) parent = ForStatement
VISIT: 'final String nb=versionNumbers[i];' [36] (VariableDeclarationStatement) parent = Block
VISIT: 'nb=versionNumbers[i]' [22] (VariableDeclarationFragment) parent = VariableDeclarationStatement
        File: null
       Tipper: DeclarationInitializerStatementTerminatingScope
       Named: DeclarationInitializerStatementTerminatingScope
        Kind: Inlining
   Described: Inline local nb into subsequent statement
 Can tip: true
    Suggests: [116, 170]
      Before: Events:
{
  for (int i=0; i < versionNumbers.length; ++i) {
    final String nb=versionNumbers[i];
    $[i]=Integer.parseInt(nb);
  }
}
 - statements:  [list change
	 [replaced: for (int i=0; i < versionNumbers.length; ++i) {
  final String nb=versionNumbers[i];
  $[i]=Integer.parseInt(nb);
}
 -> for (int i=0; i < versionNumbers.length; ++i, $[i]=Integer.parseInt(nb)) {
  final String nb=versionNumbers[i];
}
]
]

**Comment by yossigil** [comment]
Could this be related to #312? 
@sakopzon / @NivShalmon : you may be working on the same issue.

**Comment by NivShalmon** [comment]
Issue #312 is part of the bug here, but I'm trying to deal with the order in which the wrings are called. Unless we inline before moving `$[i]=Integer.parseInt(nb);` into the updaters of the for loop, we won't be inlining at all. `ExclusionManager` doesn't seem to work because ConvertForWithLastStatementUpdateToFor suggests before DeclarationInitializerStatementTerminatingScope does

**Comment by OriRoth** [comment]
@NivShalmon you can talk to me about the `ExclusionManager` and how it used in `Trimmer`. Excluding node's parent is ineffective, as you concluded.

**Comment by yossigil** [comment]
@NivShalmon : can you take over? We need a hack, not a deep solution.

**Comment by NivShalmon** [comment]
@sakopzon already solved this

**Comment by yossigil** [comment]
:+1:
