### ISSUE TITLE
Bug in compile time evaluation 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#201]
```    private long l = (long) (1L * ++d * f--);```

Try this. You will get a compile time error

**Comment by dormaayan** [comment]
@yossigil :
 After checking that issue for some time I return to my findings from the original issues:
There is a problem with wrings directly over ForStatements and WhileStatements, it seems like during running it does't take into consideration in some place this 2 kind of nodes and because of that, every wring of that type is simply ignored. I found some places with functions related to the choose-wring algorithm that exclude the handling with ForStatment and WhileStatement.
Do you aware to that problem ? do you want me to try to add the support for wrings over that kind of nodes ?

**Comment by dormaayan** [comment]
@yossigil :
I tried the exact example you gave and there wasn't any problem with that, you can have a look.
I close the issue, if there is still any problem please reopen it.

**Comment by dormaayan** [comment]
@yossigil : Sorry, I see what you mean now, Im checking that

**Comment by yossigil** [comment]
Close or open?

**Comment by dormaayan** [comment]
@yossigil :
Close
