### ISSUE TITLE
Long - double casting replacement

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Spartanizer#216]
```
public long longValue() {
  return (long) 1.0;
}
```
==>
```
public long longValue() {
  return 1L * 1.0; // compilation error
}
```
Need to add as test.
Need to find all similar bugs.
**Apparently the type of `1L * 1.0` is double not long.**

**Comment by yossigil** [comment]
@NivShalmon : this is related to your wonderful `type` class. Only apply the wring if the type of  the converted value is known to be int/short/byte/char/long, but
not if it is numeric, double, float (??? OOPS not sure here) or unknown.

**Comment by NivShalmon** [comment]
The cast can be replaced safely only if the operand is integral, in any other case (such as double and float) the result may be double/float, and so the cast sould remain unchanged. 
I've added some tests and fixed this so they would pass. I don't think the double cast shouldn't have this issue since double corrupts all other numeric types.

**Comment by yossigil** [comment]
:100:
