### ISSUE TITLE
Bug in batch spartanizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#246]
It does not print the percent as string (function p).  The CSV summarizer has this property that if all values are identical, it does not produce any output for the column. Should be about an hour

**Comment by yossigil** [comment]
https://github.com/SpartanRefactoring/Spartanizer/blob/7a36250e46166f998de36415f705600934acc99a/src/main/java/il/org/spartan/spartanizer/application/BatchSpartanizer.java

**Comment by M4tt30rru** [comment]
@yossigil do you want me to change the CSVStatistics classes on spartan?

**Comment by M4tt30rru** [comment]
@yossigil So, as far as I understand, there are two points here:

1) % is not being printed out? I think that maybe because % is used as a separator for the hashmap (in CSVWriter). 
However, I am able to change it in spartan because there are several compilation errors (i.e. the file il.org.spartan.utils.___ is missing in the source code). Also in Travis, it is not building anymore since few days. So I am not able to build another jar and place it in Spartanizer.

2) Summarizer does not print a column if all the values are equal. Is this an issue or is it OK as it is?

**Comment by yossigil** [comment]
To really understand, do two things:

- implements tests
- examine the RAW csv files

**Comment by yossigil** [comment]
:100:
