### ISSUE TITLE
User defined tippers

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#250]
The idea is that the user writes something like
```java
find 
   expression  
        X != null ? X : Y 
replaceBy by
    take(X).defaultingTo(Y) 
```
or something similar in XML, and then the user can define rules to find nanos such as `defualtsTo`

**Comment by yossigil** [comment]
@orimarco : this is the only way to generate tests for new wrings, which are nano patterns. The cycle time for creating wrings is unreasonable for this. Please allocate time for this. It is important.

**Comment by yossigil** [comment]
@M4tt30rru : this is what i spoke about, the identification of nanos.

**Comment by yossigil** [comment]
@orimarco : notice that:
- [ ]  I used Lola like syntax
- [ ] All we need is some hacking to quickly implement the nanos. It does not have to be through a language.

**Comment by orimarco** [comment]
Done.
Use `TipperFactory.tipper(pattern, replacement, description )` to create new tippers!
Adding them to the toolbox is necessary in order to make thm actually work, of course.

Example:
`TipperFactory.tipper("$X1 == null ? $X2 : $X1", "$X1.defaultsTo($X2)", "defaultsTo")` 

Notice that $X prefixes are for Expressions ans $M are for methods.
