### ISSUE TITLE
A tipper for redundant continue

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#322]
``` java
      if (!¢.wringGroup().isEnabled())
        continue;
      l.add(¢);
```

to 

``` java
      if (¢.wringGroup().isEnabled())
        l.add(¢);
```

**Comment by yossigil** [comment]
@kfir-marx : generalize this to deal with break, return and throw sequencers.

**Comment by OriRoth** [comment]
Pay attention: this works only if those two statements are *the last statements* in the loop's block (but there can be more than two!):
```Java
for (...) {
  a();
  b();
  c();
  if (!¢.wringGroup().isEnabled())
    continue;
  l.add(¢);
}
```
==>
```Java
for (...) {
  a();
  b();
  c();
  if (¢.wringGroup().isEnabled())
    l.add(¢);
}
```

**Comment by OriRoth** [comment]
By @yossigil order.

**Comment by orenafek** [comment]
@OriRoth 
@kfir-marx 
I can't find a file named `Issue322.java` anywhere in the project. 
Has this tipper never been checked ?

**Comment by orenafek** [comment]
@OriRoth 
Is this tipper already attached to the toolbox ?

**Comment by OriRoth** [comment]
1. The tipper is `EnhancedForRedundantConinue` look for tests in `Issue147.java`. I found it by temporarily replacing the tip returned from the tipper with `null`, then looked for failing tests :P you could not find the test file because this was a duplicated issue.
2. Yes. A good indication for this are passing tests that make use of `trimmingOf`, that calls the toolbox.

**Comment by orenafek** [comment]
So should I leave `ForRedundantContinue` and work only on the `Enhanced` version?

**Comment by OriRoth** [comment]
What's going on with this?
