### ISSUE TITLE
Tutorial/Testing: General test principles

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#388]
1. You do not write code without tests
2. You write the tests before you write the code.
3. All the tests are in the tests folder. No tests in the main folder
4. High coverage, use a plugin
5. You never commit code in which tests fail.
6. `@Ignore` can be used only on classes, not on particular methods

See also #391

**Comment by OriRoth** [comment]
Also I may add:
* When building a `Tipper`, it is advised to check whether adding it to the `Toolbox` break an *existing test*: the test utilities conduct only one tip at a time, so if it decide to use your new tipper instead of the original intended, the test will fail. In those cases you should fix the failing tests, while preserving the original meaning and purpose.
* When building a test class, a good idea is to include both hand-made and codes from existing projects as test cases.
