### ISSUE TITLE
Do not initailize into 'for(;;)' if this removes a final modifier

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#402]
Here is an example of actual code:
```java
          else {
            final List<Object> list = new ArrayList<>();
            final int len = Array.getLength(defaultValue);
            for (int ¢ = 0; ¢ < len; ++¢)
              list.add(Array.get(defaultValue, ¢));
            $.append(list);
          }
```

**Comment by OriRoth** [comment]
In my opinion, this is a problem that should be solved in the side effects detection mechanism.

**Comment by yossigil** [comment]
I think it can be reduced to checking whether modifier `final` eist

**Comment by dngreenst** [comment]
@yossigil The problem I have observed with the example that you have provided, is that the modifier is extended to the other initializer, not that it disappears. 

Source of the problem was that it was checked that the initializer's list of modifiers is contained in the inline candidate's, not that the two lists are equal. Fixed now.

**Comment by yossigil** [comment]
:-1: OK,  delivering to next semester.

Mission: make this bad tipping go away.

**Comment by sakopzon** [comment]
@yossigil you right, the only modifier can be used in for loop is final, so I removed the comparing loop, and added a check for final or empty modifiers. Added a few tests, to ensure it's working.

**Comment by yossigil** [comment]
:+1:
