### ISSUE TITLE
Inlining assignment into next assignment

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#449]
Here is an example

``` java
    public String getShortClassName() {
      String $ = getUTF8(contentIndex);
      if ($ == null)
        return null;
      $ = $.replaceFirst("^[\\[]+L", "");
      $ = $.replaceAll(";$", "");
      return $.startsWith("[") ? null : $.substring($.lastIndexOf('/') + 1).replace('$', '.');
    }
```

**Comment by orimarco** [comment]
implemented with Leonidas:
[BlockInlineStatementIntoNext](https://github.com/SpartanRefactoring/Spartanizer/blob/master/src/main/java/il/org/spartan/spartanizer/tippers/BlockInlineStatementIntoNext.java)

The only drawback is that because the pattern matches the while block that contain those two statements, graphically the whole block is marked blue instead of only the two statements which are to be inlined into each other.
