### ISSUE TITLE
TDD: Finding all parameter dependencies of a MethodInvocation

### ISSUE THREAD

**Issue by orimarco** [SpartanRefactoring/Spartanizer#692]
A function named 

``` Java
public Set<Name> invocations(MethodInvocation i);
```
Which:
- takes a single parameter, which is a `MethodInvocation `.
- returns a `Set<Name>` which are names of anything `i`'s parameters depend on excluding Method names.

This function is to be implemented as a static member of `tdd.getAll`.

You might want to take a look at [this](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FMethodInvocation.html).

**Comment by OriRoth** [comment]
@orimarco can you give an example?

**Comment by orimarco** [comment]
input:
```Java
foo(a+b,x, y(c), 1, bar(h,j(i)))
```
output:
`{a, b, x, c, h, i}`

**Comment by viviansh** [comment]
@orimarco  can you give us a hint how to distinguish between literals and variables, in the ASTVisitor?

**Comment by viviansh** [comment]
@orimarco We faced a problem with Name comparison in the generic Set, and asked a lecturer and another student if they knew how to fix it but couldn't help us, so we changed it to return Set<String> instead.

**Comment by OriRoth** [comment]
*Some comments*:
* Would be relevant if you'll decide to continue working on the *Spartanizer* project (and in general probably).
* As I said, you could have resolved the issue by using a `Map` from `String`s to `Name`s, then returning the values of the map (Names). Remember to verify changes in demands with your client - even if the change is legitimate as in this case.
* Moreover you should *not* miss a chance to add tests for your code - especially examples offered by your client:
* As you can see for the example of @orimarco above, dealing with Java code may be tough. Next time consider using an `ASTVisitor` in order to conduct a full tour of the `AST`, as Ori has done in his example (this is also a great practice of the 'visitor' pattern). That way you will not miss any nodes along the way - I saw that you implemented a recursive solution, but as you can see it does not cover all the cases.

**Comment by yossigil** [comment]
As I said, I don't think this code is close to being working.

**Comment by viviansh** [comment]
@yossigil we have changed the function, if u can look at it again

**Comment by yossigil** [comment]
No,  I won't take a look. Show me the tests that failed and are now working. It is not the examiner that checks, it is the test class.

**Comment by yossigil** [comment]
@AdiOmari: closing this. It is going nowhere.
