### ISSUE TITLE
Spartanizer building workspace hangs

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#764]
While trying to save our work, this window opens and the progress bar is stuck, preventing us from saving the new work

![14937832_10207427387150823_2031824946_n 1](https://cloud.githubusercontent.com/assets/15859817/19978603/328c1a6a-a200-11e6-9d60-a4f108523deb.jpg)

any thoughts ?
@orimarco 
@OriRoth

**Comment by OriRoth** [comment]
Restart, wait for the plugin to build, then work normally. Hopefully this is a one time issue...
Tell me whether you could work it out.

**Comment by OriRoth** [comment]
Remember to bless all mighty Eclipse upon success.

**Comment by amirsagiv83** [comment]
Its not a one time issue, every time im opening Eclipse, its stuck on 40% building workspace. 
amy suggestions?

**Comment by M4tt30rru** [comment]
@amirsagiv83 try to run eclipse from the command line with -clean option. Besically this: 
`./eclipse -clean`
Sometimes, it works.

**Comment by OriRoth** [comment]
As Matteo said: this rebuilds all plugins. Another option is to add `-clean` flag at the start of `eclipse.ini` file, located in eclipse's installation folder (though you should remember to remove it asap, for performances).

**Comment by amirsagiv83** [comment]
I tried this solutions but it didnt work, still stuck during the building workspace process :(

**Comment by M4tt30rru** [comment]
You can try to run eclipse from the command line with the `-consoleLog` option to print out the log messages and find out what is going on "under the hood", so to speak. 
You also should be able to find a log here: `.metadata/.log or eclipse/configuration/*.log`.
If you are really at a sticking point, and you are confident on what you are doing, you can consider to delete some content of the .metadata folder and restart eclipse. I did it in the past and it worked. Moreover, I found a bunch of discussions on StackOverflow about Eclipse hanging at startup. Have a look at them but consider that some of them are very old. I can not be more specific about which file to delete since I do not have specific information about this issue. However, this **might** be an option but  **be careful while deleting files in this directory** (maybe do an experiment on a copy of your system).

**Comment by OriRoth** [comment]
@orenafek well? I actually encountered a similar problem that was not caused by the Spartanizer but rather by lacking the eclipse SDK while trying to compile the Spartanizer code. Do you still have issues with the plugin? If it is solved tell us what you think happened and close this issue.

**Comment by orenafek** [comment]
@OriRoth
As I formatted my laptop, I have no idea what solved the problem.
