### ISSUE TITLE
il.org.spartan.spartanizer.engine->MethodScanner.java(Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by Lidkin5** [SpartanRefactoring/Spartanizer#831]
assignment 2 #799 
current coverage 0%

**Comment by yossigil** [comment]
I am not sure it is the best class to test. Proceed tiptoeing your way.

**Comment by Lidkin5** [comment]
is il.org.spartan.spartanizer.ast.navigate->count.java good enough ? @yossigil

**Comment by nikitadizhur** [comment]
We have found out that count.java was already taken. Is it fine to use engine.Make.java? @yossigil

**Comment by yossigil** [comment]
check first that it is not taken, and then check if the class is used and where, what it should do, tests on it, etc.

**Comment by nikitadizhur** [comment]
So can we use then engine.MethodScanner.java? @yossigil

**Comment by alexvitho** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/23102830/20279548/a208e328-aab1-11e6-967f-fb712d0f32af.png)

Code full covered, the yellow markers states issues that we cannot cover because those are J.B.C operations that EclEmma cannot validate. (According to http://stackoverflow.com/questions/16988041/sonar-branch-coverage-on-class-declaration).

**Comment by yossigil** [comment]
:100:

**Comment by nikitadizhur** [comment]
Current coverage: 97.7%.
