### ISSUE TITLE
il.org.spartan.spartanizer.tippers->CastBlockSingletonVariableDefinition.java (Assignment 2) Code Coverage

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Spartanizer#835]
Code coverage for il.org.spartan.spartanizer.tippers.CastBlockSingletonVariableDefinition.java, starting from 0.0%.
#799

**Comment by yossigil** [comment]
Good job and good Karma

**Comment by mdoron** [comment]
@yossigil We think we found a small bug:
`Block n = az.block(wizard.ast("{}"));
final List<Statement> ss = statements(n);`
Now, as we understand, `ss` should be an empty list, but it's not.
Did we understand correctly?

**Comment by yossigil** [comment]
:100: Indeed a bug. Now to be super ראש גדול, i.e., kama :) you can, open an issue.  create a test class with an @Ignore annotation, and with one test method that demonstrates the problem. Mark the issue open with the appropriate labels, and assign it to me.

Even opening an issue with the demo failing code in the issue and assigning it to me, is good. Actually, this is better quicker option than letting you with messing with the details of labeling and milestones.
Unless of course you  are in the plugin project and think the first option is the best use of your time ( @dormaayan, you are bored, try to pick on this one)

The rationale is: You found a bug. You should not waste time on it now, just because you found it now. Throw it to the backlog, but since the backlog manager is me, you should best do so.

**Comment by dormaayan** [comment]
@yossigil 
@mdoron  :
Great, I will take a look

**Comment by dormaayan** [comment]
@yossigil :
I think I know the source of the problem, there is a tricky thing with the conversion to Block,
The conversion actually takes all the statements and simply put them inside a Block, so for example in the case above it looks on `{ }` as a statement and simply put it inside a block.
I think its more related to the class Block that we can't change, of course.

**Comment by OriRoth** [comment]
@dormaayan no the problem is in `wizard.ast` that returns "{{}}" Block for input "{}". The fix should be applied there.

**Comment by dormaayan** [comment]
@OriRoth 
@yossigil  : 
I think I solved that bug, I added handling to the special case of empty blocks, now the wizard.ast returns `{}` over empty blocks and not `{{}}` as was before.

**Comment by mdoron** [comment]
We tested every code line that is related to this tip (we couldn't test the `go` function).
Current coverage 78.8%

**Comment by yossigil** [comment]
:100:
