### ISSUE TITLE
Fix switch tipper

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#84]
Ori, let's set a session to discuss this.

**Comment by yossigil** [comment]
@OriRoth :8ball:

**Comment by yossigil** [comment]
@OriRoth The challenge is her in thinking on how to do this right. I suggest we start with minimal options, each being a different wring.

**Comment by yossigil** [comment]
OK, here are two ideas:

- One wring to consolidate common cases. If handling is the same, then put them together, at the place of the first.
- A wring to move a case up. Moving up is done if a case is superior in one metric, and the same or better in other metrics.

Metrics are:

1. Depth, the deeper the worse.
2. Length, measured in statements, the more, the worse.
3. Length mesured in nodes, the more the worde
3. Sequencer level, only if there is one suquencer, need to ignore length in nodes in this case..


Let's try with this two, and see how it goes. There are not too many switches, so we should not worry to much. If you agree, add two new-wrings to the backlog. Give examples.

**Comment by yossigil** [comment]
default goes last.
One more metric, the number of cases.

**Comment by yossigil** [comment]
@yuvalsimon : please review the old discussion on switches above. When you are done. Close this issue.

**Comment by yuvalsimon** [comment]
@yossigil So the issue here is to make tippers for this list:
* Consolidate common cases. (#859)
* Sort cases that use the same branch (#860)
* Sort branches according to the metrics: (in this order of priority)
  1. Depth, the deeper the worse.
  2. Length, measured in statements, the more, the worse.
  3. Length mesured in nodes, the more the worse
  4. Sequencer level, only if there is one suquencer, need to ignore length in nodes in this case..
  5. Number of cases use this branch
  6. default goes last

This last tipper then cancels #861, right?
What do you mean in 1 - Depth?
And in 3 you mean to the number of nodes in the ast tree, right?
And in 4 what do you mean by sequencer level?

**Comment by yossigil** [comment]
Yes, default can go first.
Depth: nesting level height of tree.
3. yes.
4: throw/return/break/continue in this order

**Comment by yuvalsimon** [comment]
@yossigil If I have the code
```
switch(x) {
case 1:
commands
case 2:
other_commands
}
```
Then it would be a little bit more challenging to check that case 2 branch is not contained in case 1 branch (need to check that all possible execution paths of the commands before case 2 end in a sequencer). Do you want that I'll do it or assume last statement is a sequencer or otherwise branch if case 2 is contained in case 1?
Also, if I have case 2 is contained in case 1, then I should treat all the commands from case 1 to the end of commands of case 2 as one branch for comparing with the metrics, right?

**Comment by OriRoth** [comment]
If I got it correctly, you should spartanize
```Java
switch(x) {
case 1:
  f();
  return 1;
case 2:
  return 1;
}
```
into
```Java
switch(x) {
case 1:
  f();
case 2:
  return 1;
}
```
It would be easy to detect such cases, if you start comparing the Statements lists from the end ;)

**Comment by yuvalsimon** [comment]
No, the tipper only sorts the branches according to the metrics above. I have to consider also number of statements for example, so if another branch is contained in the first one (such as the second code you wrote) then I must not seperate them (and probably consider case 1 branch including case 2 branch)

**Comment by yossigil** [comment]
I am not convinced it is a good idea to introduce fall throughs, but it may be useful if there is only on fall through.
