### ISSUE TITLE
What is the auxiliary layer to use AST library?

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Spartanizer#844]
- Consists of functions like: iz, az, step (any more?)
- Can it be used in IntelliJ?
- Do you think we will need to expand it for the sake of our project?

**Comment by yossigil** [comment]
A good answer would be  a small Wiki page in the current project. Talk to @orimarco: He has a library that converts everything to the new layer.

**Comment by amirsagiv83** [comment]
**Conclusions from investigating iz.java:**
As @yossigil  already said, this is part of a huge layer built above the ASTNode library to make it's use more fluent, easy and intuitive.
the class contains a large number of mostly simple getters which allows the user to investigate easily the kind of block the plugin is currently checking. for example, if you're looking at a variable deceleration statement and you want to know whether this variable is set to be final, you can use: 

```
static boolean final¢(final VariableDeclarationStatement ¢) {
    return ¢ != null && (Modifier.FINAL & ¢.getModifiers()) != 0;
  }
```

instead of writing the check yourself. 
the library offers you a lot of very useful services, helping you investigating all kinds of blocks, if's, loops, infix exp. , and any other kind of block you can find in a java code, some of them, we already saw and experienced during the last assignment.

using it in InteliJ: the class is a long but its a simple java code that depends on itself (calling inner methods) and constants of ASTNode such as STATIC,PRIVATE,IF_STATEMENT etc, this means that if we create our own AST library or we use a different library then the one used in Eclipse, it will need adjustments, but only simple ones such as changing names of constants.

**Comment by yossigil** [comment]
Class `step`?

**Comment by amirsagiv83** [comment]
**Conclusions from investigating step.java:**
So, this class is more about extracting parts of the code with a purpose or a title, I'll try to explain myself.
Using this class you can extract conditions from loops and if statements, you can extract an operand from an infix Expression or any other similar thing.
It also gives you the option to get Lists of field's names, or method parameter's names.
I think that the difference of this class than the other 2 already described above is, that this class can hep you get inner parts of the code, as long as you know the specific type of code you are currently working on. for example, you are able to get a condition out of the for loop, but you have to use a ForStatement type to do that:
```
public static Expression condition(final ForStatement ¢) {
    return ¢.getExpression();
  }
```
you can also get the loop body, expression and any other part of a loop structure.
using it in InteliJ: same as the others, the class depends on itself and the ASTNode library, it will need the small adjustments similar to those i described above.

**Comment by amirsagiv83** [comment]
We can see that the ast library created by @yossigil  above the Eclipse ASTNode Library is separated into 3 packages:
1. Safety
2. Navigate
3. Factory

 az.java and iz.java belong to the safety package. as described above, their services allows you to make casts, check for modifiers, handle numbers and other attributes that can be associated with safety part of analyzing code. if makes sure you're not using nulls and makes the use of the nodes more safe and of course comfortable.

step.java as expected belongs to the Navigate package. together with many other .java files such as, wizzard.java , have.java, haz.java etc. , this package is responsible for navigating through the code services. it allows you to get ant information about the code, conditions, names, structures, types, methods, classes, types of expressions and more.
Using the package you can analyse dipper parts of the code and navigate through every part of it, even the smallest parts.

**Comment by yossigil** [comment]
facotry is for creating new ASTs from existing ones. Actually, creating rewriters. the most important class is "subjec" קרא במלעיל

But there are others. Usage examples should help.

**Comment by yossigil** [comment]
Ok, I think this is good enough.
