### ISSUE TITLE
Remove redundant branch in switch

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#858]
Input 
```java
switch (E) {
  case a:
    something();
    break;
  case b: 
    somethingElse();
    break;
default:
    something();
    break;
}
```

to 

```java
switch (E) {
  case b: 
    somethingElse();
    break;
default:
  case a:
    something();
    break;
}
```

**Comment by orimarco** [comment]
Bug:
```Java
    switch (m) {
	case UNNECESSARY:
		checkRoundingUnnecessary(approxCmp == 0);
	case FLOOR:
	case DOWN:
		return $;
	case CEILING:
	case UP:
		return approxPow.equals(x) ? $ : $ + 1;
	case HALF_DOWN:
	case HALF_UP:
	case HALF_EVEN:
		BigInteger x2 = x.pow(2);
		BigInteger halfPowerSquared = approxPow.pow(2).multiply(BigInteger.TEN);
		return (x2.compareTo(halfPowerSquared) <= 0) ? $ : $ + 1;
	default:
		throw new AssertionError();
	}
```
Seems to tip to itself, whats causes an infinite loop.
@yuvalsimon commented out from toolbox, please re-add it when fixed.

**Comment by yuvalsimon** [comment]
@yossigil The tipper I coded will also merge code of cases that are contained in another cases, for example if X, Y are several commands `case 1: X Y break; case 2: y break; -> case 1: X case 2: Y break;`
for example
```
switch(x) {
case 1: x=1; y=1; break;
case 2: y=1; break;
}
```
goes to
```
switch(x) {
case 1:x=1; case 2: y=1;
}
```

**Comment by yossigil** [comment]
This producs a warning...

**Comment by yuvalsimon** [comment]
@yossigil It produces warning for the contained case, like case 2 above. Should I add //$FALL-THROUGH$ to suppress it or cancel it?
Also, what should I do about comments in the code? the tipper I wrote will consider two cases as having identical code only if the comments are identical as well.  
For the current sprint I will change the tipper so that it will do only what we see in the first comment (so we won't get warnings), such that `switch(x) { case 1: x=2; case 2: y=2; break; case 3: y=2; }` goes to `switch(x) { case 1: x=2; y=2; break; case 2: case 3: y=2; } `. Alright?

**Comment by yossigil** [comment]
@yuvalsimon: not sure why you did this. merging cases and fall through in branch is difficult, and I think your code goes into an infinite loop. Also, this was not requested. I had a reason why I did not place this one.

**Comment by yossigil** [comment]
:+1:
