### ISSUE TITLE
Sorting branches in switch.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#861]
This is different then sorting labels of the same branch.
Input
```java
switch(a) { case b: a++; b++; return 1; case c: a++; return 2; }
```
Here you sort first by length of branch body, and only if this is the same, you resort to label branch sorting

Edit:
The tipper will sort branches according to the metrics: (in this order of priority)
  1. Depth, the deeper the worse.
  2. Length, measured in statements, the more, the worse.
  3. Length mesured in nodes, the more the worse
  4. Sequencer level, only if there is one suquencer, need to ignore length in nodes in this case..
  5. Number of cases use this branch
  6. default goes last

**Comment by yuvalsimon** [comment]
@yossigil I'm not sure I understood well the priority and metrics. I did what that I understood, checkout the test case. 
This is what I did:
1. default branch always goes last.
2. if only one sequencer is used in the branch (and also in the branch we compare to) then the priority order is throw, return, break, continue (in that order)
If there is no level defined for sequencer or the sequencers levels are equal: (otherwise it's decided already)
3. Compare depth of trees, which from what I understood in #84, it is the height of the ast tree (height of the statement in the branch with maximum height). the deeper the worse. 
4. Compare the length in statements - including nested statements (i.e count also statements inside a block statement).
5. Compare number of ast nodes in the in the branches. 
6. Compare number of cases that use this branch (not including fall through statements). 
7. I will add now - if no decision made, compare by hash code so that we won't get to infinite loop. 

Is it alright?

**Comment by yuvalsimon** [comment]
Will add it back to toolbox tomorrow, I have to go over other switch tippers tests so they won't fail

**Comment by yuvalsimon** [comment]
@yossigil In which package should I put the Branch class that I implemented for this tipper? It could be useful for other switch tippers.

**Comment by yossigil** [comment]
Maybe in wizard? Or, at least in its package? Or `extract`

**Comment by yuvalsimon** [comment]
Ok I moved it to wizards's package
