### ISSUE TITLE
Use listrewrite to sort annotations

### ISSUE THREAD

**Issue by kobybs** [SpartanRefactoring/Spartanizer#881]
Current Implementation of #283 doesn't use listrewrite to sort the elements. This may lead to comments being lost.

**Comment by danabramovich** [comment]
@yossigil I didnt use ListRewrite mainly because I did not understand how to sort it , instead I used only ASTRewrite. If it is not the solution can you please elaborate more on what should I do with ListRewrite

**Comment by yossigil** [comment]
Search for all uses of listrerwrite in the code. This is what I would do to remember how to use it,which I don't....

**Comment by danabramovich** [comment]
Does the tests I've committed mean that comments are being preserved ?

**Comment by yossigil** [comment]
No, because tests remove comments...

**Comment by danabramovich** [comment]
I went over the places in the code where ListRewrite was used and I still don't understand what I should do with it.

**Comment by yossigil** [comment]
Ok. If you cannot deal with this we will let someone else do it.

**Comment by yossigil** [comment]
@danabramovich  Here is a full blown example: https://github.com/SpartanRefactoring/Spartanizer/blob/8117129ab8a2f57394c2530215ef85e6af078202/laconization-cases/SortElementsOperation.java

**Comment by danabramovich** [comment]
yes I've already seen that class, Ill go over it again. Is this Issue still due by wednesday?

**Comment by OriRoth** [comment]
YES I will contact you tomorrow about it.

**Comment by yossigil** [comment]
Yes. It is stil ldue.

@danabramovich when you say somehting such as "I went over the code and did not understand it", there is not much people cand do to help you, because you did not say what the problem was, and what efforts you made, nor what was the specific prolem. 

In saying such a thing, you say "I cannot do it, becasue I am not capable enough", and you may prove a burden to your fellow team mate. A more ccoperative way of dealing with issues of this sort would be:

- Tell more about the specific efforts you made and the specific problem.
- Say that your are too busy to deal with it.
- Ask a specific question, rather than say "I can't".

@idabran @AdiOmari @yh-github @orimarco @zvili

**Comment by danabramovich** [comment]
Ok, so before I made the first commit I've spend five to six hours reading every single line of code in the project containing ListRewrite, plus I asked Ori Roth for help. I also **specifically** asked how can I get the ListRewrite of annotations, plus you said you would be happy to help me, so I asked for help because I've had spend a lot of time on this issue and I have other things I have to do.

**Comment by danabramovich** [comment]
Anyways Today I going to finish this issue...

**Comment by yossigil** [comment]
`@yossigil Ok, so before I made the first commit I've spend five to six hours reading every single line of code in the project containing ListRewrite and reading the documentation of ListRewrite ans ASTRewrite, plus I asked Ori Roth for help. I also specifically asked how can I get the ListRewrite of annotations, plus you said you would be happy to help me, so I asked for help because I've had spend a lot of time on this issue and I have other things I have to do.`


@danabramovich,  the 5--6 hours you spent on this are not necessrily a good thing. IMHO, spending so much time on learning code, does not say good things about the reader. I prefer to not believe you on this, since I have regard for your capabilities beyond the 5--6 hours.

As to find the attribute of annotations, IMHO, this could have taken a very short while. Let me try doing so, and tell you what I think.

More genrally, and I would like to involve all staff members in this: @orimarco @AdiOmari @zvili @idabran  and @yh-github, in many cases,  something very specific has to be said to make sure students take resonsibility of issues they are assigned.

Taking responsiblity never means: "I posted a question and I was waiting for an answer".  "I did not ge the help I expected", "I do not understand what to do", etc.

Taking responsibility means yes, using help, but not putting the person you ask for help to be responsible for what you do.

_

**Comment by yossigil** [comment]
Right after the posting the the above comment, but not before it, I started working on the annotations thingy. Took me two- three google searches to get this:

https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=JDT+EXTENDEDMODIFIER+PROPERTY&nfpr=1

**Comment by danabramovich** [comment]
@yossigil @OriRoth Done.

I have ran the improved tipper on this piece of code:
```

@SuppressWarnings("static-method") //comment
/**
 * comment
 * comment
 * comment
 * comment
 * comment
 * @author comment
 * @param int x
 */
@Deprecated /*comment comment comment
comment comment*/

public class rerwrwerw {
}
```

and after spartanizing I got:

```
/**
 * comment
 * comment
 * comment
 * comment
 * comment
 * @author comment
 * @param int x
 */
@Deprecated /*comment comment comment
comment comment*/
@SuppressWarnings("static-method") //comment

public class rerwrwerw {
}
```

**Comment by OriRoth** [comment]
Looks great, nice job!

**Comment by yossigil** [comment]
Brilliant :100:
