### ISSUE TITLE
Redundant continue in a labeled For loop 

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Spartanizer#882]
This test doesn't work :
`loop: for (;;) continue loop; `
see Issue #147 for the tipper

**Comment by orenafek** [comment]
@OriRoth 
OK ?

**Comment by yossigil** [comment]
Super job @orenafek

**Comment by yossigil** [comment]
See this failing test:
```java
  @Test public void labeledStatementShouldntTip() {
    trimmingOf("x -> {loop: for(;;) continue loop;}") //
        .stays();
  }
```

**Comment by orenafek** [comment]
The test above can be found in `Issue455.java` (#455)

**Comment by yossigil** [comment]
I took it out from this file so as to make our test suite clean

**Comment by mdoron** [comment]
@yossigil @orimarco I fixed the bug, but whoever built this Tipper didn't do it right. After my change the Tipper now offers correction in the right way, but the "Apply" button doesn't do anything. 
I think it's a bug for another issue, but because of the way we test our Tippers I cannot test the **offering** alone.
I tried to fix the "Apply" button myself but didn't managed to do so. 
I also called @OriRoth but he couldn't do his job as tutor at that moment, so I send this comment and hope for help.

**Comment by mdoron** [comment]
@yossigil Another think - I did some "Rosh Gadol" if it okay...
Instead of canceling this Tipper when there is a labeled continue, I reached to the parent of the ForStatement and asked if it is a LabeledStatement. If so, I checked whether the label of the labeled continue and the label of the ForStatement are the same or not, and if so, I told the Tipper to advice a removal of redundant continue statement

**Comment by dormaayan** [comment]
@mdoron : The code you just  upload in the last commit doesn't compile, both on travis and on my-computer

**Comment by mdoron** [comment]
@dormaayan Passed compilation on my machine, maybe I ctrl+s with mistake and uploaded it without noticing. 
But nvm that, because I just fixed this Tipper for good, so I'm writing some tests and uploading it all together.

**Comment by mdoron** [comment]
@dormaayan how do I test the case that I don't want the tipper to change my code?
for example - loop: for (;;) loop2: for(;;) continue loop;

**Comment by dormaayan** [comment]
@mdoron : you can use` .stays()` instead of `.gives("something")`

**Comment by mdoron** [comment]
Grazie.
Commiting now.

**Comment by yossigil** [comment]
:100:
