### ISSUE TITLE
Switch with only one case with optional default.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#916]
Convert
```java
switch (x) {
case y: f();
break;
default:
z();
}
```
into an `if` ... `else`

**Comment by yuvalsimon** [comment]
@yossigil Is it ok if the tipper puts the if-else inside a block, assuming it will be inlined by the block inlining tipper? Is it ok in general usually?

**Comment by yuvalsimon** [comment]
Also, should I convert
```
switch (x) {
case y: f();
}
```
to if statement? (I already did it but disabled it for now)

**Comment by yuvalsimon** [comment]
Ok so I decided for now not to convert such switch statement as above to if statement.
For now the tipper is only for such case as in the first comment (i.e only when there are 2 cases, one of them is default), but could be expanded later for `switch(x) { case 1: case 2: case 3: f(); break default: g(); `} to convert to if-else (because there are 2 execution path, one of them is default)
