### ISSUE TITLE
Bug in switch-case

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#967]
```java
  private static String buildMessage(final String kind, final String... args) {
    String $ = kind + " ";
    switch (args.length) {
      case 0:
        break;
      case 1:
        $ += args[0];
        break;
      default:
        final Object os[] = new Object[args.length - 1];
        for (int ¢ = 1; ¢ < args.length; ++¢)
          os[¢ - 1] = args[¢];
        final Formatter f = new Formatter();
        f.format(args[0], os);
        $ += f.out();
    }
    return $;
  }
```
Feed the abbove, it erases everything!

**Comment by yossigil** [comment]
Actually, it is in 'inline into'

**Comment by yuvalsimon** [comment]
I see the problem, I think it's my fault. Should I fix it?

**Comment by yuvalsimon** [comment]
I believe the bug is because of #880 , so the tipper (the bug was in the issue itself, the code was ok). I will create a test case for this issue tomorrow to be certain it does not occur. Also I added some code to SwitchEmpty which relied on #880 to remove empty cases, so now it will remove `switch(x) { case a: break; case b: case c: }` and treat side effects as before.  
I will also check tomorrow that #880 did not make any bug somewhere else.

**Comment by yuvalsimon** [comment]
It's alright
